task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

# num_classes: 365
# remap_mscoco_category: False

# num_classes: 91
# remap_mscoco_category: False

num_classes: 5
remap_mscoco_category: False


train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /mnt/pool1/czk/poledet/dataset/coco/campus_coco_v1/train2017
    ann_file: /mnt/pool1/czk/poledet/dataset/coco/campus_coco_v1/annotations/filtered_train_coco.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 3
  drop_last: True 
  collate_fn:
    type: BatchImageCollateFuncion


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /mnt/pool1/czk/poledet/dataset/coco/campus_coco_v1/val2017
    ann_file: /mnt/pool1/czk/poledet/dataset/coco/campus_coco_v1/annotations/val_coco.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~ 
  shuffle: False
  num_workers: 3
  drop_last: False
  collate_fn:
    type: BatchImageCollateFuncion
